# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='status',
            field=models.IntegerField(choices=[(1, b'In use'), (2, b'Returned'), (3, b'Redeemed')], default=1),
            preserve_default=False,
        ),
    ]
