# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.IntegerField(choices=[(1, b'Plastic Bottle'), (2, b'Cardboard'), (3, b'Cans')]),
        ),
    ]
