# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='appuser',
            name='encrypted_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
