# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_auto_20170630_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
