# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='account_uuid',
            new_name='code',
        ),
    ]
